[package]
name = "vault-server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.7", features = [
    "redis-rs-session",
    "redis-rs-tls-session",
], optional = true }
actix-identity = { version = "0.5", optional = true }
actix-web = { version = "4.3" }
actix-cors = { version = "0.6" }

chrono = { version = "0.4.20", features = ["serde"] }
derive_more = { version = "0.99.7" }
diesel = { version = "2", features = [
    "postgres",
    "r2d2",
    "uuid",
    "chrono",
    "serde_json",
], optional = true }
env_logger = { version = "0.10" }
log = "0.4"
once_cell = "1"
r2d2 = { version = "0.8", optional = true }
rust-argon2 = "1"
serde_json = { version = "1" }
serde = { version = "1" }
time = { version = "0.3" }
uuid = { version = "1", features = ["v4", "serde"] }
sendgrid = { version = "0.19", optional = true }
diesel_migrations = { version = "2.0", optional = true }
regex = "1.7.3"
openai_dive = { version = "0.2.3", features = ["stream"], optional = true }
tokio = "1.27.0"
tokio-stream = "0.1.12"
futures-util = "0.3.28"
async-stream = "0.3.5"
actix = "0.13.0"
futures = "0.3.28"
crossbeam-channel = "0.5.8"
qdrant-client = { version = "1.3.0", optional = true }
rust-s3 = { version = "0.33.0", optional = true }
base64 = "0.21.2"
glob = "0.3.1"
itertools = "0.11.0"
redis = { version = "0.23.1", features = ["tokio-rustls-comp"] }
reqwest = { version = "0.11.18", features = ["json"] }
rand = "0.8.5"
dotenvy = "0.15.7"
simsearch = "0.2.4"
lazy_static = { version = "1.4.0" }
actix-files = "0.6.2"
utoipa = { version = "4", features = [
    "actix_extras",
    "uuid",
    "chrono",
    "debug",
] }
utoipa-redoc = { version = "1.0", features = ["actix-web"] }
magick_rust = { version = "0.19.1", optional = true }
pyo3 = { version = "0.20.0", features = [
    "full",
    "auto-initialize",
], optional = true }
cfg-if = "1.0.0"

[build-dependencies]
dotenvy = "0.15.7"

[features]
default = ["ingest-server"]
monolith = [
    "dep:pyo3",
    "dep:magick_rust",
    "dep:qdrant-client",
    "dep:rust-s3",
    "dep:sendgrid",
    "dep:openai_dive",
    "dep:diesel_migrations",
    "dep:diesel",
    "dep:r2d2",
    "dep:actix-session",
    "dep:actix-identity",
]
runtime-env = []
ingest-server = []
